// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MejdisiIm.Models;

public partial class Comment
{
    public int? CommentId { get; set; }

    public int ReportId { get; set; }

    public int UserId { get; set; }

    public string Content { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual EnvironmentalReport Report { get; set; }

    public virtual User User { get; set; }
}