// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MejdisiIm.Models;

public partial class EnvironmentalReport
{
    public int? ReportId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public string ImageUrl { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int UserId { get; set; }

    public int CategoryId { get; set; }

    public virtual ReportCategory Category { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual User User { get; set; }

    public virtual ICollection<Vote> Votes { get; set; } = new List<Vote>();
}