// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MejdisiIm.Models;

public partial class GreenTip
{
    public int? TipId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Category { get; set; }
}