// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MejdisiIm.Models;

public partial class RecyclingCenter
{
    public int? CenterId { get; set; }

    public string Name { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public string Address { get; set; }

    public string Contact { get; set; }
}