// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MejdisiIm.Models;

public partial class ReportCategory
{
    public int? CategoryId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<EnvironmentalReport> EnvironmentalReports { get; set; } = new List<EnvironmentalReport>();
}