// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MejdisiIm.Models;

public partial class User
{
    public int? UserId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string Role { get; set; } = "Costumer";

    public virtual ICollection<UserSession> UserSessions { get; set; } = new List<UserSession>();

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<EnvironmentalReport> EnvironmentalReports { get; set; } = new List<EnvironmentalReport>();

    public virtual ICollection<Vote> Votes { get; set; } = new List<Vote>();
}